POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxhcyIsImlkIjoiNjA1MWY1MDBkYzM2ZjQxNjNjOWE4Mjg4IiwiaWF0IjoxNjE2MDAzNTY3fQ.4CaY1DW4swVoxCd4HcSQ3jCsUGpBItveMr1lkx273XI

{
  "title": "This is my third post with middleware and token auth",
  "author": "Frank L. Wright",
  "url": "https://web.com",
  "likes": 5,
  "userId": "6051f500dc36f4163c9a8288"
}
